import { AgentRanksOutput, BusinessFact, FactCategory } from "@agentranks/core";

export interface MarkdownFiles {
  "ai-profile.md": string;
  "products.md": string;
  "services.md": string;
  "pricing.md": string;
  "faqs.md": string;
  "policies.md": string;
  "use-cases.md": string;
  "differentiators.md": string;
}

export function generateMarkdownFiles(output: AgentRanksOutput): MarkdownFiles {
  const grouped = groupByCategory(output.facts);
  const meta = buildMeta(output);

  return {
    "ai-profile.md": generateAiProfile(output, grouped, meta),
    "products.md": generateCategoryDoc("Products", "product", grouped, meta),
    "services.md": generateCategoryDoc("Services", "service", grouped, meta),
    "pricing.md": generatePricingDoc(grouped, meta),
    "faqs.md": generateFaqDoc(grouped, meta),
    "policies.md": generateCategoryDoc("Policies", "policy", grouped, meta),
    "use-cases.md": generateCategoryDoc("Use Cases", "use_case", grouped, meta),
    "differentiators.md": generateCategoryDoc("Key Differentiators", "differentiator", grouped, meta),
  };
}

// ─── Helpers ──────────────────────────────────────────────────────────────────

type Grouped = Partial<Record<FactCategory, BusinessFact[]>>;

interface Meta {
  name: string;
  url: string;
  description?: string;
  generatedAt: string;
}

function buildMeta(output: AgentRanksOutput): Meta {
  return {
    name: output.business.name,
    url: output.business.url,
    description: output.business.description,
    generatedAt: output.generatedAt,
  };
}

function groupByCategory(facts: BusinessFact[]): Grouped {
  const grouped: Grouped = {};
  for (const fact of facts) {
    if (!grouped[fact.category]) grouped[fact.category] = [];
    grouped[fact.category]!.push(fact);
  }
  return grouped;
}

function frontmatter(meta: Meta, title: string): string {
  return [
    "---",
    `title: "${title} — ${meta.name}"`,
    `source: "${meta.url}"`,
    `generated: "${meta.generatedAt}"`,
    `agentranks: true`,
    "---",
    "",
  ].join("\n");
}

function factList(facts: BusinessFact[], showSource = false): string {
  if (!facts || facts.length === 0) {
    return "_No information extracted for this category._\n";
  }
  return facts
    .map((f) => {
      let line = `- **${f.claim}**`;
      if (f.detail) line += `\n  ${f.detail}`;
      if (showSource) line += `\n  *Source: [${f.sourceUrl}](${f.sourceUrl})*`;
      return line;
    })
    .join("\n") + "\n";
}

function confidenceNote(facts: BusinessFact[]): string {
  if (!facts || facts.length === 0) return "";
  const avg = facts.reduce((s, f) => s + f.confidence, 0) / facts.length;
  return `\n> **Data quality:** ${facts.length} facts, avg. confidence ${(avg * 100).toFixed(0)}%\n`;
}

// ─── Generators ───────────────────────────────────────────────────────────────

function generateAiProfile(
  output: AgentRanksOutput,
  grouped: Grouped,
  meta: Meta
): string {
  const lines: string[] = [];
  lines.push(frontmatter(meta, "AI Profile"));
  lines.push(`# ${meta.name} — AI Profile\n`);

  if (meta.description) {
    lines.push(`> ${meta.description}\n`);
  }

  lines.push(`**Website:** [${meta.url}](${meta.url})\n`);

  const companyFacts = grouped["company_profile"] ?? [];
  if (companyFacts.length > 0) {
    lines.push("## Company Overview\n");
    lines.push(factList(companyFacts));
  }

  const diffFacts = grouped["differentiator"] ?? [];
  if (diffFacts.length > 0) {
    lines.push("## Why They're Different\n");
    lines.push(factList(diffFacts));
  }

  const prodFacts = grouped["product"] ?? [];
  const svcFacts = grouped["service"] ?? [];
  if (prodFacts.length + svcFacts.length > 0) {
    lines.push("## What They Offer\n");
    if (prodFacts.length > 0) {
      lines.push("### Products\n");
      lines.push(factList(prodFacts));
    }
    if (svcFacts.length > 0) {
      lines.push("### Services\n");
      lines.push(factList(svcFacts));
    }
  }

  const pricingFacts = grouped["pricing"] ?? [];
  if (pricingFacts.length > 0) {
    lines.push("## Pricing\n");
    lines.push(factList(pricingFacts));
  }

  const useCaseFacts = grouped["use_case"] ?? [];
  if (useCaseFacts.length > 0) {
    lines.push("## Use Cases\n");
    lines.push(factList(useCaseFacts));
  }

  const integrationFacts = grouped["integration"] ?? [];
  if (integrationFacts.length > 0) {
    lines.push("## Integrations\n");
    lines.push(factList(integrationFacts));
  }

  const locationFacts = grouped["location"] ?? [];
  if (locationFacts.length > 0) {
    lines.push("## Locations\n");
    lines.push(factList(locationFacts));
  }

  lines.push("---");
  lines.push(`\n*Generated by AgentRanks on ${meta.generatedAt}*\n`);
  lines.push(`*Total facts: ${output.summary.totalFacts} | Pages scanned: ${output.summary.pagesScanned}*\n`);

  return lines.join("\n");
}

function generateCategoryDoc(
  title: string,
  category: FactCategory,
  grouped: Grouped,
  meta: Meta
): string {
  const facts = grouped[category] ?? [];
  const lines: string[] = [];
  lines.push(frontmatter(meta, title));
  lines.push(`# ${title}\n`);
  lines.push(`**Company:** [${meta.name}](${meta.url})\n`);
  lines.push(confidenceNote(facts));
  lines.push(factList(facts, true));
  lines.push("---");
  lines.push(`\n*Generated by AgentRanks on ${meta.generatedAt}*\n`);
  return lines.join("\n");
}

function generatePricingDoc(grouped: Grouped, meta: Meta): string {
  const facts = grouped["pricing"] ?? [];
  const lines: string[] = [];
  lines.push(frontmatter(meta, "Pricing"));
  lines.push(`# Pricing — ${meta.name}\n`);
  lines.push(`**Company:** [${meta.name}](${meta.url})\n`);
  lines.push(confidenceNote(facts));

  if (facts.length === 0) {
    lines.push("_No pricing information was extracted from the website._\n");
    lines.push(
      `_Visit [${meta.url}](${meta.url}) for current pricing details._\n`
    );
  } else {
    lines.push(factList(facts, true));
  }

  lines.push("---");
  lines.push(`\n*Generated by AgentRanks on ${meta.generatedAt}*\n`);
  return lines.join("\n");
}

function generateFaqDoc(grouped: Grouped, meta: Meta): string {
  const facts = grouped["faq"] ?? [];
  const lines: string[] = [];
  lines.push(frontmatter(meta, "FAQs"));
  lines.push(`# Frequently Asked Questions — ${meta.name}\n`);
  lines.push(`**Company:** [${meta.name}](${meta.url})\n`);
  lines.push(confidenceNote(facts));

  if (facts.length === 0) {
    lines.push("_No FAQ entries were extracted from the website._\n");
  } else {
    for (const fact of facts) {
      lines.push(`## ${fact.claim}\n`);
      if (fact.detail) lines.push(`${fact.detail}\n`);
      lines.push(
        `*Source: [${fact.sourceUrl}](${fact.sourceUrl})*\n`
      );
    }
  }

  lines.push("---");
  lines.push(`\n*Generated by AgentRanks on ${meta.generatedAt}*\n`);
  return lines.join("\n");
}
